repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/pkolomytsev/pre-commit-shfmt
    rev: v3.8.0.0
    hooks:
      - id: shfmt
  - repo: https://github.com/pkolomytsev/pre-commit-shellcheck
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.2.0
    hooks:
      - id: biome-check
