name: Continuous Integration
on:
  push:
    branches:
      - main
    paths:
      - "**/*_test.ts"
  pull_request:
jobs:
  run_tests_and_upload_codecov:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          bun install
          bun test --coverage
      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
